#!/bin/sh

STATUS="$(nmcli -t -f type,state,connection d | egrep "^(tun|tap):connected" | awk -F':' '{ print $3 }')"
COLOR="#FF0000"
VPN0="\ue0a9VPN"
VPN1="\ue1b8VPN"

if [[ -z $STATUS ]]; then
    echo -e $VPN0 
    echo 
    echo $COLOR
fi
if [[ -n $STATUS ]]; then
    echo -e $VPN1
fi
