#!/bin/bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

#INTERFACE="${BLOCK_INSTANCE:-wlan0}"

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
#[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
#    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit

#------------------------------------------------------------------------

#QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
QUALITY=$(grep wlp3s0 /proc/net/wireless | awk '{ print int($3 * 100 / 70)}')

#------------------------------------------------------------------------

#echo -en "\ue219$QUALITY%" # full text
#echo -en "\ue048$QUALITY%" # short text

function cnet() {
    ping -c 1 209.132.183.105 | grep "100% packet loss"
}

function dns() {
    nslookup www.google.com | grep SERVFAIL
}

if [[ -n "$(cnet)" || -n "$(DNS)" ]]; then
    echo -e "\ue1BA??"
    echo -e "\ue1BA??"
    echo "#FF0000"
    exit 0
else
    echo -e "\ue1BA$QUALITY%" # short text
fi

#if [[ $QUALITY -lt 10 ]]; then
#    echo -e "\ue1BAROUTER?"
#    echo -e "\ue1BAROUTER?"
#    echo "#FF0000"
#else
#    echo -e "\ue1BA$QUALITY%" # short text
#fi

# color
#if [[ $QUALITY -ge 80 ]]; then
#    echo "#87d7ff"
#elif [[ $QUALITY -lt 80 ]]; then
#    echo "#87d7ff"
#elif [[ $QUALITY -lt 60 ]]; then
#    echo "#ffaf00"
#elif [[ $QUALITY -lt 40 ]]; then
#    echo "#ffaf00"
#else
#    echo "#ff0000"
#fi

