# ~/.tmuxinator/daily.yml

name: tmux
root: ~/

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Project hooks
# Runs on project start, always
# on_project_start: command
# Run on project start, the first time
# on_project_first_start: command
# Run on project start, after the first time
# on_project_restart: command
# Run on project exit ( detaching from tmux session )
# on_project_exit: command
# Run on project stop
# on_project_stop: command

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: editor

# Specifies (by index) which pane of the specified window will be selected on project startup. If not set, the first pane is used.
# startup_pane: 1

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

# Runs after everything. Use it to attach to tmux with custom options etc.
# post: tmux -CC attach -t daily

windows:
  - td:
      # layout: 5e00,317x73,0,0[318x37,0,0{158x37,0,0,0,159x37,159,0,3},318x36,0,38{158x36,0,38,4,159x36,159,38,5}]]
      # Synchronize all panes of this window, can be enabled before or after the pane commands run.
      # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
      # synchronize: after
      panes:
        - calcurse
        #- mutt
        #- sleep 20 && clear && mocp
        #- sleep 20 && /home/chris/.scripts/mpd_launcher
  #- logs: vim "+normal G" /home/chris/.admin_log.txt
  - lg: sleep 5;pause;vim '+normal G' /home/chris/User/Logs/.admin_log.txt
  #- bk: sleep 5;pause;vim '+normal G' /home/chris/.bookmarks_backup.html
  - sw: 
    #  - cl: sleep 5;pause;/home/chris/.scripts/calorie_day_log
#  - irc: weechat
#  - bug:
#      layout: 85ff,318x74,0,0{159x74,0,0,11,158x74,160,0[158x36,160,0,10,158x37,160,37,6]}
#      panes:
  # - rd: sleep 5;pause;ranger /home/chris/Documents/Notes/
  #  - wk: sleep 5;pause;uolo
  #  - ^1:
  #     panes:
  #       - pause;dotgit;clear
  #       - ranger "/home/chris/.sources/dotfiles"
         #  - ^2:
         #     panes:
         #       - pause;lgmgit;clear
         #       - ranger "/home/chris/.sources/csmertx.github.io"
         #  - ^3:
    #panes:
    #  -
    #  - ranger
#  - server: bundle exec rails s
#  - logs: tail -f log/development.log
