#!/bin/bash

# Automate with Crontab, Systemd, etc.

# ex: crontab -e
# 0 */1 * * * /home/user/.scripts/moon_phase.sh
# Add to Tmux theme via: #(cat '/dev/shm/moon_phase_parsed.txt')
# Or however you add scripts to Tmux

wotd="/dev/shm/wordoftheday.txt"
wotdu="/dev/shm/wordoftheday.url"

# Loader text
echo "WOTD: Loading..." > $wotd
wget -q -O- https://www.merriam-webster.com/word-of-the-day > $wotdu

# Parse out WOTD
wordoftheday="$(cat $wotdu \
| perl -lne 'print $1 if /<title>(.*)/' \
| grep "Word" \
| sed "s/.*: //g" \
| sed "s/ |.*//g")"

# Print to file
echo "WOTD: Loading..." > $wotd
sleep 2
echo "WOTD: $wordoftheday" > $wotd
if [[ ! "$(cat $wotd | awk '{print $2}')" ]]; then
        echo "WOTD: ..404.." > $wotd
fi
